### ISSUE TITLE
Ubuntu 16.04 install issue

### ISSUE THREAD

**Issue by telegraphic** [kiyo-masui/bitshuffle#52]
I am having trouble getting bitshuffle to work on a new 16.04 machine. When I run a test, I get the following error:

```
In [11]: h5.create_dataset(f, "range", shape, dtype, chunks,
    ...:                   filter_pipeline=(32008, 32000),
    ...:                   filter_flags=(h5z.FLAG_MANDATORY, h5z.FLAG_MANDATORY),
    ...:                   filter_opts=None)
/usr/local/bin/ipython:4: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  import re
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: H5Pocpl.c line 1039 in H5Pget_filter_by_id2(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: H5Pint.c line 3817 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: H5Pint.c line 3767 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
```

I am using python 2.7.12, h5py v2.6.0, HDF5 v1.10.0-patch1. I received the same error message when using using the stock libhdf5 from apt (`apt-get install libhdf5-serial-dev`). Bitshuffle was installed with and without the `--h5plugin` flag

Any idea what is causing this, or a plan of attack?

**Comment by kiyo-masui** [comment]
H5py 2.6 has a bunch of issues. These seem to be fixed in h5py master and
don't exist in 2.5, so try that.

**Comment by telegraphic** [comment]
This was indeed a local install issue (apologies!), that arose due to my quest to solve a hdf5 library issue (https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide).

My solution was a fresh install from source of hdf5, h5py, and then bitshuffle.

**Comment by Kriechi** [comment]
I'm also getting this error. @telegraphic did you start with a fresh & clean machine, or is there a way to fix this manually without reinstalling my whole system?

**Comment by Kriechi** [comment]
Nope - doesn't even work on a fresh Ubuntu 16.04 VM:
Using the example from the README, I get this output when run in an python3.5 interpreter:

```
2.7.1
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140421521086208:
  #000: ../../../src/H5Pocpl.c line 1102 in H5Pget_filter_by_id2(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: ../../../src/H5Pint.c line 3381 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: ../../../src/H5Pint.c line 3331 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
```

Fresh Ubuntu 16.04, `libhdf5-serial-dev` installed, and bitshuffle master branch installed with `python3 setup.py install --h5plugin`
